### ISSUE TITLE
Dependency error for 9.4.53-jre11

### ISSUE THREAD

**Issue by rtheobald** [jetty/jetty.docker#187]
Trying to build image with `logging-log4j` but am getting a 404 error

Looks like `https://repo1.maven.org/maven2/org/slf4j/slf4j-log4j12/1.7.36/slf4j-log4j12-1.7.36.jar` has been moved

I'm guessing the `pom` file is normally parsed to deal with a redirect:

```<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
<script/>
<modelVersion>4.0.0</modelVersion>
<parent>
<groupId>org.slf4j</groupId>
<artifactId>slf4j-parent</artifactId>
<version>1.7.36</version>
</parent>
<artifactId>slf4j-log4j12</artifactId>
<packaging>pom</packaging>
<name>SLF4J LOG4J-12 Binding relocated</name>
<description>SLF4J LOG4J-12 relocated to slf4j-reload4j</description>
<url>http://www.slf4j.org</url>
<distributionManagement>
<relocation>
<groupId>org.slf4j</groupId>
<artifactId>slf4j-reload4j</artifactId>
<version>1.7.36</version>
</relocation>
</distributionManagement>
</project>```

**Comment by rtheobald** [comment]
I should have been using `--add-to-start=logging-log4j2` which solved my particular issue.

I'll leave this issue open as I believe it should still work with the older version of log4j.

**Comment by joakime** [comment]
Jetty 9.x is at End of Community Support (since June 2022)

* jetty/jetty.project#7958

This issue will not be fixed in Jetty 9.x

Note: this specific dependency issue has already been fixed in Jetty 10 and newer already.
https://github.com/jetty/jetty.project/blob/jetty-10.0.x/jetty-home/src/main/resources/modules/logging-log4j1.mod
