### ISSUE TITLE
curl in Jetty 9 images has medium CVE

### ISSUE THREAD

**Issue by michaelmior** [jetty/jetty.docker#208]
Docker Scout flags the installed version of curl in jetty:9-jre8-alpine as having a medium severity CVE. Since curl (and I think gnupg also) are only needed during the setup process, can they be removed once they are used?

**Comment by joakime** [comment]
Jetty 9 is at End of Community Support.

* https://github.com/jetty/jetty.project/issues/7958

**Comment by michaelmior** [comment]
@joakime Okay, thanks for the notice. Looks like then this won't be fixed.
