### ISSUE TITLE
JDK 22 support

### ISSUE THREAD

**Issue by sergey-morenets** [jetty/jetty.docker#211]
Hi

Do you have any plans to support JDK 22 in your Docker images? Currently only JDK 21 and earlier versions are supported.

**Comment by lachlan-roberts** [comment]
I think its best we only support this for Jetty 12 versions, as Jetty 9, 10 & 11 are EOCS.
I will open a PR and we can discuss from there if any additional images should be added.

**Comment by lachlan-roberts** [comment]
@sergey-morenets JDK22 images are now EOL, so now we are dropping support for JDK22 and adding support for JDK23.
See https://github.com/jetty/jetty.docker/commit/9c0344d032b14a8f13681e820fd81e9778140e7f
